analyse/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("urls/", views.analyseUrl, name="anUrl"),
    path("emoji/search/", views.searchEmoji, name="searchEmoji"),
    path("emoji/extract/", views.extractEmoji, name="extractEmoji"),
    path("stopwords/", views.getStopWords, name="stopwords"),
    path("text/overview/", views.overviewText, name="overviewT"),
    path("text/analyze/", views.dataSetAnalysis, name="datasetT"),
    path("extract/", views.getDataset, name="upload"),
]

api/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path("result/<str:task_id>/", views.getMainTaskResponse, name="task-result"),
    path(
        "analysis/<str:task_id>/", views.getAnalysisTaskResponse, name="analysis-result"
    ),
    path(
        "keywords/<str:task_id>/", views.getKeywords, name="keywords-result"
    ),
    path(
        "file/<int:pid>/", views.getCsvColumns, name="csv-columns"
    ),
]

django_advertools/urls.py
from django.contrib import admin
from django.urls import path, include
from django.http import HttpResponse
from django.conf import settings
from django.conf.urls.static import static
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View


def index(request):

    return render(request, "home.html")

def reset_cookie(request):
    response = redirect("home")
    # Delete the existing cookie
    print(request.COOKIES)
    if 'socket_id' in request.COOKIES:
        del request.COOKIES['socket_id']
        response.delete_cookie(key='socket_id')
    
    # Set a new cookie with desired parameters
    # response.set_cookie('cookie_name', 'new_value', max_age=3600)
    
    return response


def serveReport(request):
    return render(request, "reportMain.html")


def getReport(request):
    return render(request, "report.html")


urlpatterns = [
    path("", index, name="home"),
    path("report/get/", getReport, name="getReport"),
    path("report/", serveReport, name="report"),
    path("reset/cookie/",reset_cookie,name="reset-cookie"),
    path("select2/", include("django_select2.urls")),
    path("analyse/", include("analyse.urls")),
    path("seo/", include("seo.urls")),
    path("api/", include("api.urls")),
    path("generate/", include("generateAds.urls")),
    path("admin/", admin.site.urls),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

analyse/models.py
from django.db import models

# Create your models here.


class DatasetFile(models.Model):
    file_title = models.CharField(max_length=250)
    file_field = models.FileField(upload_to="datasets/", unique=True)
    added_dt = models.DateTimeField(auto_now_add=True)

    class Meta:
        unique_together = ["file_title", "file_field", "added_dt"]

    def __str__(self):
        return self.file_title + " " + str(self.file_field)

analyse/forms.py
from django import forms
from .models import DatasetFile


class AnalyseUrls(forms.Form):
    urls = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "rows": 10,
                "cols": 40,
                "placeholder": "Enter urls in new lines like  \nhttp://localhost:8000/generate/advertisement/large/\nhttps://importsem.com/create-a-custom-twitter-tweet-alert-system-with-python/",
            }
        )
    )

    decode = forms.BooleanField(required=False)


class EmojiSearch(forms.Form):
    emoji_text = forms.CharField(
        widget=forms.TextInput(
            attrs={"placeholder": 'Enter Emoji you want to view like "vegetable" '}
        )
    )


class EmojiExtract(forms.Form):
    emoji_text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "rows": 10,
                "cols": 40,
                "placeholder": "Enter text you want to extract emoji from in new lines like\nI am grinning 😀\nA grinning cat 😺\nhello! 😀😀😀 💛💛\nJust text",
            }
        )
    )


class TextAnalysis(forms.Form):
    valid_text = forms.CharField(
        widget=forms.Textarea(
            attrs={
                "rows": 7,
                "cols": 40,
                "placeholder": "Enter text you want to analyze if seperately seperate it in new lines like\nI am grinning 😀\nA grinning cat 😺\nhello! 😀😀😀 💛💛\nJust text",
            }
        )
    )

    phrase_len = forms.IntegerField(max_value=10, required=False)


class DatasetExtract(forms.ModelForm):
    class Meta:
        model = DatasetFile
        fields = ["file_title", "file_field"]


class DatasetSelect(forms.Form):
    file_title = forms.ModelChoiceField(queryset=DatasetFile.objects.all().order_by('-id'))
    column_name = forms.ChoiceField(choices=[("---","---")])

analyse/views.py
from django.shortcuts import render

# Create your views here.
from django.contrib import messages
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import HttpResponse
from advertools import (
    url_to_df,
    emoji_search,
    extract_emoji,
    stopwords,
    word_frequency,
    extract_intense_words,
    extract_hashtags,
    extract_mentions,
    extract_numbers,
    extract_questions,
    extract_urls,
)
from .forms import (
    AnalyseUrls,
    EmojiSearch,
    EmojiExtract,
    TextAnalysis,
    DatasetExtract,
    DatasetSelect,
)
from .utils import url_structure
from .models import DatasetFile
import pandas as pd


def analyseUrl(request):
    if request.method == "POST":
        form = AnalyseUrls(request.POST)
        if form.is_valid():
            urls = form.cleaned_data["urls"]
            urls = list(map(str.strip, urls.split("\n")))
            # urls = [url for url in urls if url.startswith("http","www")]

            decode = form.cleaned_data["decode"]

            df = url_to_df(urls=urls, decode=decode)
            try:
                figure = url_structure(df).to_html()
            except KeyError:
                figure = None

            return render(
                request,
                "analyse/anUrl.html",
                {
                    "form": form,
                    "figure": figure,
                    "urlsDf": df.to_html(
                        classes="table table-striped text-center", justify="center"
                    ),
                },
            )

    else:
        form = AnalyseUrls()
        return render(request, "analyse/anUrl.html", {"form": form})


def searchEmoji(request):
    if request.method == "POST":
        form = EmojiSearch(request.POST)
        if form.is_valid():
            emoji_text = form.cleaned_data["emoji_text"]

            df = emoji_search(emoji_text)

            return render(
                request,
                "analyse/emoji.html",
                {
                    "form": form,
                    "emojiDf": df.to_html(
                        classes="table table-striped text-center", justify="center"
                    ),
                },
            )

    else:
        form = EmojiSearch()
        return render(request, "analyse/emoji.html", {"form": form})


def extractEmoji(request):
    if request.method == "POST":
        form = EmojiExtract(request.POST)
        if form.is_valid():
            emoji_text = form.cleaned_data["emoji_text"]
            emoji_text = list(map(str.strip, emoji_text.split("\n")))
            df = extract_emoji(emoji_text)
            # print(df)
            df = pd.DataFrame.from_dict(df, orient="index")
            df = df.transpose()
            return render(
                request,
                "analyse/emojiExtract.html",
                {
                    "form": form,
                    "emojiDf": df.to_html(
                        classes="table table-striped text-center", justify="center"
                    ),
                },
            )

    else:
        form = EmojiExtract()
        return render(request, "analyse/emojiExtract.html", {"form": form})


def getStopWords(request):
    if request.method == "GET":
        stopwords_list = stopwords
        df = pd.DataFrame.from_dict(stopwords_list, orient="index")
        df = df.transpose()
        return render(
            request,
            "analyse/stopwords.html",
            {
                "df": df.to_html(
                    classes="table table-striped text-center", justify="center"
                )
            },
        )
    else:
        return HttpResponse("Ínvalid request Type")


def overviewText(request):
    if request.method == "POST":
        form = TextAnalysis(request.POST)
        if form.is_valid():
            valid_text = form.cleaned_data["valid_text"]
            valid_text = list(map(str.strip, valid_text.split("\n")))
            phrase_len = form.cleaned_data["phrase_len"]

            df = pd.DataFrame()
            if phrase_len:
                df = word_frequency(valid_text, phrase_len=phrase_len, extra_info=True)
            else:
                df = word_frequency(valid_text, extra_info=True)

            messages.success(request, "text Overview generated")

           
            return render(
                request,
                "analyse/textan.html",
                {
                    "form": form,
                    #  'json': jsonD,
                    "textDf": df.to_html(
                        classes="table table-striped text-center", justify="center"
                    ),
                },
            )

    else:
        form = TextAnalysis()
        return render(request, "analyse/textan.html", {"form": form})


def getDataset(request):
    if request.method == "POST":
        form = DatasetExtract(request.POST, request.FILES)
        
        if form.is_valid():
            
            data, created = DatasetFile.objects.get_or_create(**form.cleaned_data)
            # print(data)
            if created:
                messages.success(request, f"The dataset has been successfully added")
            else:
                messages.warning(
                    request,
                    f"The dataset {data.file_title}:{data.file_field} already exits.",
                )
            
            return redirect("datasetT")
        else:
            print(form.cleaned_data)
            return HttpResponse("form invalid")
    else:
        form = DatasetExtract()
        return render(request, "analyse/extraction.html", {"form": form})


def dataSetAnalysis(request):
    submission = False

    form = DatasetSelect()
    if request.method == "POST":
        # print(form.cleaned_data)

        form_data = request.POST

        dataset_val = form_data.get("file_title")

        column_name = form_data.get("column_name")

        try:
            dataset_val = DatasetFile.objects.get(id=int(dataset_val))

            df = pd.read_csv(dataset_val.file_field.path)
            # print(df)
            df.dropna(subset=[column_name], inplace=True)

            listCol = df[column_name].to_list()
            

            urls = extract_urls(listCol)
            mentions = extract_mentions(listCol)
            questions = extract_questions(listCol)
            numbers = extract_numbers(listCol)
            hashtags = extract_hashtags(listCol)
            intense_words = extract_intense_words(
                listCol, min_reps=3
            )  # minimum repertition of words 3

            submission = True

            return render(
                request,
                "analyse/analyzeText.html",
                {
                    "form": form,
                    "textDf": df.to_html(
                        classes="table table-striped text-center", justify="center"
                    ),
                    "submission": submission,
                    "urls": urls,
                    "mentions": mentions,
                    "questions": questions,
                    "numbers": numbers,
                    "hashtags": hashtags,
                    "intense_words": intense_words,
                },
            )
        except Exception as e:
            
            messages.warning(request, e)
            return render(
                request,
                "analyse/analyzeText.html",
                {
                    "form": form,
                    "textDf": df.to_html(
                        classes="table table-striped text-center", justify="center"
                    ),
                },
            )

    else:
        return render(
            request,
            "analyse/analyzeText.html",
            {"form": form, "submission": submission},
        )

analyse/templates/analyse/anUrl.html
{% extends "base.html" %}
{% load static %}


{% block css %}

{% endblock css %}

{% load crispy_forms_tags %}
{% block pageContent %}
<div class="container">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6 ">
                <form method="post">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4 main-t">Analyse URLs</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">
                            Analyse
                        </button>
                    </div>
                </form>
            </div>
            <div class="col-md-12 mt-4" style="width:100%;overflow-x: scroll;">
                {% if figure %}
                    {{ figure | safe }}
                {% endif %}
            </div>
            <div class="col-md-12 mt-4" style="width:100%;overflow-x: scroll;">
                {% if urlsDf %}
                    {{ urlsDf | safe }}
                {% endif %}
            </div>

        </div>
    </div>
</div>
{% endblock pageContent %}

{% block javascript %}




{% endblock javascript %}

analyse/templates/analyse/analyzeText.html
{% extends "base.html" %}
{% load static %}
{% load custom_filters %}


{% block css %}
<style>
.order-card {
    color: #fff;
}

.bg-c-blue {
    background: linear-gradient(45deg,#4099ff,#73b4ff);
}

.bg-c-green {
    background: linear-gradient(45deg,#2ed8b6,#59e0c5);
}

.bg-c-yellow {
    background: linear-gradient(45deg,#FFB64D,#ffcb80);
}

.bg-c-pink {
    background: linear-gradient(45deg,#FF5370,#ff869a);
}

.card {
    border-radius: 5px;
    -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);
    box-shadow: 0 1px 2.94px 0.06px rgba(4,26,55,0.16);
    border: none;
    margin-bottom: 30px;
    -webkit-transition: all 0.3s ease-in-out;
    transition: all 0.3s ease-in-out;
}

.card .card-block {
    padding: 25px;
}

.order-card i {
    font-size: 26px;
}

.f-left {
    float: left;
}

.f-right {
    float: right;
}
</style>

{% endblock css %}

{% load crispy_forms_tags %}
{% block pageContent %}
<div class="container-fluid">
    <div class="container-fluid">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6 ">
                <form method="post">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4 main-t">Text Analysis from dataset column</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">
                            Analyze
                        </button>
                        <hr />
                        <p>OR</p>
                        <hr />
                        <a class="btn btn-info" href="{% url 'upload' %}">
                            Upload
                        </a>
                    </div>
                </form>
            </div>
            {% if submission %}
            <div class="col-md-12 mt-4">
                <div class="row d-flex justify-content-center">
                    <h2 class="h2 mb-2 text-center">Text Overview</h2>
                    <div class="col-md-4 col-xl-4">
                        <div class="card bg-c-green order-card">
                            <div class="card-block">
                                <h6 class="m-b-20">URLs found</h6>
                                <h2 class="text-right"><i class="fa fa-link f-left"></i><span class="px-2">{{ urls.overview.num_urls }}</span></h2>
                                <p class="m-b-0">Urls per post<span class="f-right">{{ urls.overview.urls_per_post }}</span></p>
                                <p class="m-b-0">Unique Urls<span class="f-right">{{ urls.overview.unique_urls }}</span></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-xl-4">
                        <div class="card bg-c-yellow order-card">
                            <div class="card-block">
                                <h6 class="m-b-20">Mentions found</h6>
                                <h2 class="text-right"><i class="fa fa-quote-left f-left"></i><span class="px-2">{{ mentions.overview.num_mentions}}</span></h2>
                                <p class="m-b-0">Mentions per post<span class="f-right">{{ mentions.overview.mentions_per_post}}</span></p>
                                <p class="m-b-0">Unique Mentions<span class="f-right">{{ mentions.overview.unique_mentions }}</span></p>
                            </div>
                        </div>
                        
                    </div>
                    <div class="col-md-4 col-xl-4">
                        <div class="card bg-c-pink order-card">
                            <div class="card-block">
                                <h6 class="m-b-20">Questions found</h6>
                                <h2 class="text-right"><i class="fa fa-question f-left"></i><span class="px-2">{{ questions.overview.num_question_marks}}</span></h2>
                                <p class="m-b-0">Questions per post<span class="f-right">{{ questions.overview.question_marks_per_post}}</span></p>
                                <p class="m-b-0">Unique Questions<span class="f-right">{{ questions.overview.unique_question_marks }}</span></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-xl-4">
                        <div class="card bg-c-blue order-card">
                            <div class="card-block">
                                <h6 class="m-b-20">Hashtags found</h6>
                                <h2 class="text-right"><i class="fa fa-hashtag f-left"></i><span class="px-2">{{ hashtags.overview.num_hashtags}}</span></h2>
                                <p class="m-b-0">Hashtags per post<span class="f-right">{{ hashtags.overview.hashtags_per_post}}</span></p>
                                <p class="m-b-0">Unique Hashtags<span class="f-right">{{ hashtags.overview.unique_hashtags }}</span></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-xl-4">
                        <div class="card bg-c-green order-card">
                            <div class="card-block">
                                <h6 class="m-b-20">Numbers found</h6>
                                <h2 class="text-right"><i class="fa fa-arrow-up f-left"></i><span class="px-2">{{ numbers.overview.num_numbers}}</span></h2>
                                <p class="m-b-0">Numbers per post<span class="f-right">{{ numbers.overview.numbers_per_post}}</span></p>
                                <p class="m-b-0">Unique Numbers<span class="f-right">{{ numbers.overview.unique_numbers }}</span></p>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-4 col-xl-4">
                        <div class="card bg-c-yellow order-card">
                            <div class="card-block">
                                <h6 class="m-b-20">Intense Words found</h6>
                                <h2 class="text-right"><i class="fa fa-repeat f-left"></i><span class="px-2">{{ intense_words.overview.num_intense_words}}</span></h2>
                                <p class="m-b-0">Intense Words per post<span class="f-right">{{ intense_words.overview.intense_words_per_post}}</span></p>
                                <p class="m-b-0">Unique Intense Words<span class="f-right">{{ intense_words.overview.unique_intense_words }}</span></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endif %}
            <div class="col-md-12 mt-4" style="max-height: 600px;overflow-y: scroll;">
                {% if textDf %}
                    {{ textDf | safe }}
                {% endif %}
            </div>

            <div class="col-md-12 mt-4">
                <div class="row d-flex justify-content-center mt-2">
                    {% if urls.urls_flat %}
                    <div class="col-md-6 col-sm-12 col-xl-4" style="max-height: 450px;overflow-y: scroll;">
                        <h5 class="h5">
                            URLs 
                        </h5>
                        <ul class="list-group list-group-flush">
                            {% for url in urls.urls_flat %}
                            <li class="list-group-item">{{ url }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                    {% if mentions.mentions_flat %}
                    <div class="col-md-6 col-sm-12 col-xl-4" style="max-height: 450px;overflow-y: scroll;">
                        <h5 class="h5">
                            Mentions 
                        </h5>
                        <ul class="list-group list-group-flush">
                            {% for url in mentions.mentions_flat %}
                            <li class="list-group-item">{{ url }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                    {% if questions.question_marks_flat %}
                    <div class="col-md-6 col-sm-12 col-xl-4" style="max-height: 450px;overflow-y: scroll;">
                        <h5 class="h5">
                            Questions
                        </h5>
                        <ul class="list-group list-group-flush">
                            {% for question in question_marks.question_marks_flat %}
                            <li class="list-group-item">{{ question }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                    {% if hashtags.hashtags_flat %}
                    <div class="col-md-6 col-sm-12 col-xl-4" style="max-height: 450px;overflow-y: scroll;">
                        <h5 class="h5">
                            Hashtags 
                        </h5>
                        <ul class="list-group list-group-flush">
                            {% for hashtag in hashtags.hashtags_flat %}
                            <li class="list-group-item">{{ hashtag }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                    {% if numbers.numbers_flat %}
                    <div class="col-md-6 col-sm-12 col-xl-4" style="max-height: 450px;overflow-y: scroll;">
                        <h5 class="h5">
                            Numbers 
                        </h5>
                        <ul class="list-group list-group-flush">
                            {% for number in numbers.numbers_flat %}
                            <li class="list-group-item">{{ number }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                    {% if intense_words.intense_words_flat %}
                    <div class="col-md-6 col-sm-12 col-xl-4" style="max-height: 450px;overflow-y: scroll;">
                        <h5 class="h5">
                            Intense Words 
                        </h5>
                        <ul class="list-group list-group-flush">
                            {% for intense in intense_words.intense_words_flat %}
                            <li class="list-group-item">{{ intense }}</li>
                            {% endfor %}
                        </ul>
                    </div>
                    {% endif %}
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock pageContent %}

{% block javascript %}

<script>

    $('#id_file_title').on('change', function (e) {
        
        
        var optionSelected = $("option:selected", this);
        
        var valueSelected = this.value;
        var url = "/api/file/"+valueSelected+"/";
        console.log(url);
        fetch(url)
        .then((response) => response.json())
        .then((data) => {
          console.log(data);
          // const content = JSON.parse(data);
          const element = document.getElementById("id_column_name");

          let html = `<option value selected>------</option>`;
          
          data.result.forEach(column=>{
            html+= `<option value="${column}">${column}</option>`
          })

          element.innerHTML = html;

        //   applyDataTablesFormatting(element);
          // initializeDatatables();
        })

        .catch((error) => {
          console.error("Error:", error);
        });
    });
// var fileSelector = document.getElementById("id_file_title");
// fileSelector.onchange((e)=>{

// })

</script>


{% endblock javascript %}

analyse/templates/analyse/emoji.html
{% extends "base.html" %}
{% load static %}


{% block css %}

{% endblock css %}

{% load crispy_forms_tags %}
{% block pageContent %}
<div class="container">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6 ">
                <form method="post">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4 main-t">Search Emoji</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">
                            Search
                        </button>
                    </div>
                </form>
            </div>
            <div class="col-md-12 mt-4" style="max-height: 700px;overflow-y: scroll;">
                {% if emojiDf %}
                    {{ emojiDf | safe }}
                {% endif %}
            </div>

        </div>
    </div>
</div>
{% endblock pageContent %}

{% block javascript %}




{% endblock javascript %}

analyse/templates/analyse/emojiExtract.html
{% extends "base.html" %}
{% load static %}


{% block css %}

{% endblock css %}

{% load crispy_forms_tags %}
{% block pageContent %}
<div class="container">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6 ">
                <form method="post">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4 main-t">Extract Emoji</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">
                            Extract
                        </button>
                    </div>
                </form>
            </div>
            <div class="col-md-12 mt-4" style="max-height: 700px;overflow-y: scroll;">
                {% if emojiDf %}
                    {{ emojiDf | safe }}
                {% endif %}
            </div>

        </div>
    </div>
</div>
{% endblock pageContent %}

{% block javascript %}




{% endblock javascript %}

analyse/templates/analyse/extraction.html
{% extends "base.html" %}
{% load static %}


{% block css %}

{% endblock css %}

{% load crispy_forms_tags %}
{% block pageContent %}
<div class="container">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6 ">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4 main-t">DataSet Analysis</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">
                            Upload
                        </button>
                        <hr />
                        <p>OR</p>
                        <hr />
                        <a class="btn btn-info" href="{% url 'datasetT' %}">
                            Analyze
                        </a>
                    </div>
                </form>
            </div>
            

        </div>
    </div>
</div>
{% endblock pageContent %}

{% block javascript %}




{% endblock javascript %}

analyse/templates/analyse/stopwords.html
{% extends "base.html" %}
{% load static %}


{% block css %}

{% endblock css %}

{% load crispy_forms_tags %}
{% block pageContent %}
<div class="container">
    <div class="container">
        <h1 class="h1 text-bolder">StopWords</h1>
        <div class="row">
            <div class="col-md-12" style="height: 600px; overflow-y: scroll;">
                {% if df %}
                    {{ df | safe }}
                {% endif %}
            </div>

        </div>
    </div>
</div>
{% endblock pageContent %}

{% block javascript %}




{% endblock javascript %}

analyse/templates/analyse/textan.html
{% extends "base.html" %}
{% load static %}


{% block css %}

{% endblock css %}

{% load crispy_forms_tags %}
{% block pageContent %}
<div class="container">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-6 ">
                <form method="post">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="border-bottom mb-4 main-t">Text Analysis</legend>
                        {{ form|crispy }}
                    </fieldset>
                    <div class="form-group">
                        <button class="btn btn-outline-info" type="submit">
                            Analyze
                        </button>
                    </div>
                </form>
            </div>
            <div class="col-md-12 mt-4" style="max-height: 700px;overflow-y: scroll;">
                {% if textDf %}
                    <a class="btn btn-outline-secondary mb-2 mt-2" href="{% url 'report' %}">
                        View Data Profiling Report
                    </a>
                    {{ textDf | safe }}
                {% endif %}
            </div>

        </div>
    </div>
</div>
{% endblock pageContent %}

{% block javascript %}




{% endblock javascript %}